[package]
name = "dijkstra"
version = "0.1.0"
authors = ["merbaum7"]
edition = "2018"

repository = "https://github.com/RuSys/dijkstra"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
